apiVersion: v1
kind: Service
metadata:
  name: vm-victoria-metrics-single-server
  namespace: victoria-modules
  {{- include "helm_lib_module_labels" (list . (dict "app" "victoriametrics")) | nindent 2 }}
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8428
    protocol: TCP
    targetPort: http
  selector:
    {{- include "victoriametrics.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
